"""
Domain Layer - Core Entities and Protocols

Pure business logic with no external dependencies.
All interfaces defined as typing.Protocol for structural subtyping.
"""

from .entities import (
    Envelope,
    EnvelopeMetadata,
    FragmentInfo,
    FecInfo,
    CryptoInfo,
    Priority,
    RawSample,
    SensorData,
    Command,
    ActuatorAction,
    Ack,
    State,
    Pose,
    Twist,
    RobotMode,
    MissionGoal,
    GoalType,
    Task,
    TaskStatus,
    Policy,
    Detection,
    SlamPose,
    AudioEvent,
)

from .protocols import (
    ISensorAdapter,
    IActuatorPort,
    ICodec,
    ICompressor,
    IDeltaCodec,
    IFEC,
    ICryptoBox,
    IQoSShaper,
    ITransport,
    IModel,
    IYoloDetector,
    IAudioProcessor,
    IWorldModel,
    IStateEstimator,
    IGoalManager,
    ITaskPlanner,
    IScheduler,
    IPolicyManager,
    ISkill,
    IRuleChecker,
    ISafetySupervisor,
    IActionSynthesizer,
    IActionJustifier,
    INoveltyDetector,
    IHomeostasis,
    IStigmergy,
)

__all__ = [
    # Entities
    "Envelope",
    "EnvelopeMetadata",
    "FragmentInfo",
    "FecInfo",
    "CryptoInfo",
    "Priority",
    "RawSample",
    "SensorData",
    "Command",
    "ActuatorAction",
    "Ack",
    "State",
    "Pose",
    "Twist",
    "RobotMode",
    "MissionGoal",
    "GoalType",
    "Task",
    "TaskStatus",
    "Policy",
    "Detection",
    "SlamPose",
    "AudioEvent",
    # Protocols
    "ISensorAdapter",
    "IActuatorPort",
    "ICodec",
    "ICompressor",
    "IDeltaCodec",
    "IFEC",
    "ICryptoBox",
    "IQoSShaper",
    "ITransport",
    "IModel",
    "IYoloDetector",
    "IAudioProcessor",
    "IWorldModel",
    "IStateEstimator",
    "IGoalManager",
    "ITaskPlanner",
    "IScheduler",
    "IPolicyManager",
    "ISkill",
    "IRuleChecker",
    "ISafetySupervisor",
    "IActionSynthesizer",
    "IActionJustifier",
    "INoveltyDetector",
    "IHomeostasis",
    "IStigmergy",
]
